### ISSUE TITLE
It is possible to reset the EV3 without removing the battery

### ISSUE THREAD

**Issue by dlech** [nerves-project/nerves_system_ev3#9]
Hi, I am spying on projects using ev3dev today. :smile: 

I noticed in your readme that it says:

> Hanging on the EV3 forces you to remove and reinsert the batteries since there's no reboot button.

But, this is not true. If you hold the back and center buttons at the same time, it will reboot the EV3.

**Comment by fhunleth** [comment]
Thanks so much for spying on this project. I didn't know that, but that's so useful to know. I hated removing the batteries to make it reboot.
